name: Life's code
description: Code of life
url: https://yorkane.github.io/
github: 'yorkane'
comments: 'https://github.com/yorkane/yorkane.github.io'
gaaccount: 'UA-209990017-1'
comments: false
highlighter: rouge
# theme: jekyll-theme-slate

title: Life's code
url: https://yorkane.github.io
paginate: 1
baseurl: ""
permalink: pretty
timezone: Asia/Shanghai


# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - LICENSE

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: UA-209990017-1

# Specify the author for blog posts
author:
  name: Kevin Yuan
  url: https://yorkane.github.io
  email: whyork@qq.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /archive
  - title: About
    url: /about
  - title: Code
    url: https://github.com/yorkane
  - title: 404
    url: /404